### ISSUE TITLE
More explicit instructions for emacs noobs?

### ISSUE THREAD

**Issue by timholy** [gdkrmr/flycheck-julia#11]
I'm interested in this but don't really understand the installation procedure. I followed the MELPA "getting started", https://stable.melpa.org/#/getting-started, but that seems to cause some kind of error. I don't have an `init.el` file, either.

**Comment by gdkrmr** [comment]
You are right, the installation instructions are not very clear. With emacs there is always the problem that there are several ways to install it, so I will try to explain it starting from an unconfigured emacs. If the following works for you I will add it to the readme. Your init file is either `~/.emacs` or `~/.emacs.d/init.el`, if you do not have any of those, just create one of them.

Installation from a fresh emacs:
To install `flycheck` (http://www.flycheck.org/en/latest/user/installation.html), put the following into your init file:
```elisp
(require 'package)
(add-to-list 'package-archives '("MELPA Stable" . "https://stable.melpa.org/packages/"))
(add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))
(package-initialize)
```
Restart emacs and run `M-x list-packages` or choose `Options -> Manage Packages` from the menu and install `flycheck`, `ess`, and `flycheck-julia`.

Add the following to the end of your init file:
```elisp
;; loads ess, which contains ess-julia-mode
(require 'ess-site)
;; enable flycheck globally
(add-hook 'after-init-hook #'global-flycheck-mode)
;; tell flycheck about the julia linter
(flycheck-julia-setup)
```

Open or create a file with the ending `.jl`, syntax highlighting should be turned on and a julia process with the lint server should start. It will take the server a couple of seconds and a number of edits to get everything compiled, during which time emacs will be a bit choppy and there will be some error messages, but everything should be fine after ~20 seconds.

If you plan to debug the lint server, you can open the buffer `*julia-linter*` which will contain all the output as if you started the julia server from a repl.

**Comment by timholy** [comment]
(Maybe add "press `i` to choose a package and `x` to install your selections.)

When I pressed `x` I get "package emacs-25 is not available" (To be clear, I didn't manually select emacs-25, just the 3 you mentioned.)

**Comment by gdkrmr** [comment]
> (Maybe add "press i to choose a package and x to install your selections.)

From the list package buffer you can do everything nicely with the mouse.

> When I pressed x I get "package emacs-25 is not available" (To be clear, I didn't manually select emacs-25, just the 3 you mentioned.)


You probably get this message because you are probably using emacs 24 and I put emacs 25 in the requirements. Emacs 24 should be enough, I changed the requirements (695a90b). Did it work though?

Changes see: https://github.com/gdkrmr/flycheck-julia/blob/dev/README.md
This should be quite comprehensive now, anything else to add?

**Comment by timholy** [comment]
> From the list package buffer you can do everything nicely with the mouse.

Duh, right!

> Did it work though?

No, it refuses to install `flycheck-julia`. The other two work, though. I tried again this morning after that version-lowering commit, still didn't work. Is that perhaps because the instructions above tell me to use MELPA Stable, and the patch hasn't hit it or something?

**Comment by gdkrmr** [comment]
MELPA works as following: the MELPA repository gets the latest commit from the master branch and MELPA stable gets the latest tagged version. I just merged everything into master, so if you add the following line to your config:
```elisp
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
```
and do `M-x list-packages` the version on master should appear (it is the one that contains a date) as soon as MELPA rebuilds. Until then you can try if you get the manual install to work (see README.md) or get Emacs 25.

**Comment by gdkrmr** [comment]
on MELPA now

**Comment by timholy** [comment]
It's still finding the one in MELPA stable, which requires emacs-25. I even commented out that `add-to-list` line (so that `melpa` was the only choice, not `MELPA Stable`) and did another `list-packages`, but it still wanted to install 0.0.3 depending on emacs-25.

**Comment by gdkrmr** [comment]
did you restart your emacs?

The one on MELPA has only emacs 24 as a requirement: https://melpa.org/#/flycheck-julia

If you add both, the you should see both version, 0.0.3 and 20170715.xxx, an upgrade should upgrade to the MELPA version.

**Comment by timholy** [comment]
(Sorry, I forgot to hit "Comment" on this.)

Works with a restarted emacs, thanks!

But I'm not seeing any difference in the behavior of emacs when I load a `.jl` file.

**Comment by gdkrmr** [comment]
I am not sure what might be the problem without knowing your config file. You need to make a couple of edits for ~30s before the communication between Emacs and the lint server works properly.

**Comment by gdkrmr** [comment]
is it working now? please reopen if not!
